fix: correct provenance file format
Without the ... separator the `helm plugin verify` command fails with:

Error: plugin verification failed: message block must have at least two parts

Based on https://github.com/helm/helm/blob/75880fa498b511cdc4d31dd8752b4937cfb15cf9/pkg/provenance/sign_test.go#L82 and https://github.com/helm/helm/blob/75880fa498b511cdc4d31dd8752b4937cfb15cf9/pkg/provenance/sign.go#L305 we need to add this YAML document end marker.